name: Build and Release Firefox Extension

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Update manifest version from tag
        if: github.ref_type == 'tag'
        run: |
          sed -i 's/"version": "0.0.0.1"/"version": "'"${{ github.ref_name }}"'"/' manifest.json

      - name: Build unsigned artifact
        run: web-ext build --overwrite-dest --artifacts-dir ./artifacts

      - name: Delete existing release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=""
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            RELEASE_TAG="${{ github.ref_name }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            RELEASE_TAG="main"
          fi
          if [[ -n "$RELEASE_TAG" ]]; then
            echo "Deleting release $RELEASE_TAG"
            gh release delete $RELEASE_TAG -y || true
          else
            echo "Not a tag or main branch push, skipping release deletion."
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
          release_name: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
          body: ${{ github.ref == 'refs/heads/main' && github.event.head_commit.message || '' }}
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/main' }}
          latest: ${{ github.ref_type == 'tag' }}

      - name: Find Release Asset
        id: find_asset
        run: |
          ASSET_PATH=$(find ./artifacts -maxdepth 1 \( -name "*.xpi" -o -name "*.zip" \) -print -quit)
          echo "ASSET_PATH=${ASSET_PATH}" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=$(basename ${ASSET_PATH})" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_asset.outputs.ASSET_PATH }}
          asset_name: ${{ steps.find_asset.outputs.ASSET_NAME }}
          asset_content_type: ${{ endsWith(steps.find_asset.outputs.ASSET_NAME, '.xpi') && 'application/x-xpinstall' || 'application/zip' }}
